In [ ]:
#pip install yfinance

In [1]:
import yfinance as yf
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from datetime import datetime

In [23]:
data = "/Users/hp/SAD_Finance/nasdaq_screener_1686545341556.csv"
stock=pd.read_csv(data)
len(stock)

7707

In [42]:
stock1 = stock[0:1000]
stock1
stock_symbol1 = stock1["Symbol"]
symbol1 = stock_symbol1.tolist()

test_symbol = ['A','AA','AAC','AACG','AACI','AACIU','AACIW','AADI','AAIC','AAIC^B','AAIC^C','AAIN']

In [43]:
df = pd.DataFrame()

for i in symbol1:
    ticker = yf.Ticker(i)

    # Set the start and end dates for data retrieval
    start_date = datetime(2012, 1, 1)
    end_date = datetime(2016, 12, 31)

    historical_data = ticker.history(start=start_date, end=end_date, interval='1d')

    if historical_data.empty:
        continue

    historical_data['Symbol']=i
    df = df.append(historical_data)
    
df = df.reset_index()
df

df.to_csv('/Users/hp/SAD_Finance/stock_1.csv',index=False)

ERROR AAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AACI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AACIU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AACIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AADI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AAIC^B: No timezone found, symbol may be delisted
ERROR AAIC^C: No timezone found, symbol may be delisted
ERROR AAIN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AAM^A: No timezone found, symbol may be delisted
ERROR AAM^B: No timezone found, symbol may be delisted
ERROR AAMC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ABCL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ABCM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ABNB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ABOS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ABR^D: No timezone found, symbol may be delisted
ERROR ABR^E: No timezone found, symbol may be delisted
ERROR ABR^F: No timezone found, symbol may be delisted
ERROR ABSI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACAB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACABW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACACU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACACW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACAH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACAHW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACAQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACAX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACAXR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACAXU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACBA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACBAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACBAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACCD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACDC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACDCW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACEL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACET: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACGLN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACGLO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACHL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACHR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACLX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACMR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACON: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACONW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ACP^A: No timezone found, symbol may be delisted
ERROR ACR^C: No timezone found, symbol may be delisted
ERROR ACR^D: No timezone found, symbol may be delisted
ERROR ACRO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACRV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACVA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ACXP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADAG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADC^A: No timezone found, symbol may be delisted
ERROR ADCT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADER: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADERW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADEX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADIL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADILW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADNWW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADOC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADOCR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADPT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADRT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADSE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADSEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADTH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADTHW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ADVWW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ADXN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AEAE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AEAEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AEFC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AEI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AEL^A: No timezone found, symbol may be delisted
ERROR AEL^B: No timezone found, symbol may be delisted
ERROR AEPPZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AESC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AESI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AEVA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFAR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFARU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFBI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFCG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFGB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFGC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFGD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFGE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFIB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFRI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFRIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AFRM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFTR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AFYA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGAE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGBA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGBAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AGE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGFY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR AGIL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGILW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AGL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGM^C: No timezone found, symbol may be delisted
ERROR AGM^D: No timezone found, symbol may be delisted
ERROR AGM^E: No timezone found, symbol may be delisted
ERROR AGM^F: No timezone found, symbol may be delisted
ERROR AGM^G: No timezone found, symbol may be delisted
ERROR AGMH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGNCL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGNCM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGNCN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGNCO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGNCP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGRI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGRIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AGS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AGTI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AHCO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AHG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AHH^A: No timezone found, symbol may be delisted
ERROR AHI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AHL^C: No timezone found, symbol may be delisted
ERROR AHL^D: No timezone found, symbol may be delisted
ERROR AHL^E: No timezone found, symbol may be delisted
ERROR AHRN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AHRNU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AHRNW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AHT^D: No timezone found, symbol may be delisted
ERROR AHT^F: No timezone found, symbol may be delisted
ERROR AHT^G: No timezone found, symbol may be delisted
ERROR AHT^H: No timezone found, symbol may be delisted
ERROR AHT^I: No timezone found, symbol may be delisted
ERROR AI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIBBR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AIG^A: No timezone found, symbol may be delisted
ERROR AIH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIHS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIMAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIMAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AIMD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIMDW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AIO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIRC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIRS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIRTP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIXI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AIZN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AJXA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AKA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AKAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AKLI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR Failed to get ticker 'AKO/A' reason: Expecting value: line 1 column 1 (char 0)
ERROR AKO/A: No timezone found, symbol may be delisted
ERROR Failed to get ticker 'AKO/B' reason: Expecting value: line 1 column 1 (char 0)
ERROR AKO/B: No timezone found, symbol may be delisted
ERROR AKRO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AKU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AKYA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AL^A: No timezone found, symbol may be delisted
ERROR ALAR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALBT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALCC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALCYU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALEC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALGM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALGS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALHC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALIM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALIT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALKT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALL^B: No timezone found, symbol may be delisted
ERROR ALL^H: No timezone found, symbol may be delisted
ERROR ALL^I: No timezone found, symbol may be delisted
ERROR ALL^J: No timezone found, symbol may be delisted
ERROR ALLG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALLK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALLO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALLR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALOR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALORU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALORW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ALPA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALPAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALPAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ALPP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALPS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALRN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALSA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALSAR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ALSAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ALT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALTG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALTG^A: No timezone found, symbol may be delisted
ERROR ALTI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALTIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ALTR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALTU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALTUU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALTUW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALVO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALVOW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ALVR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALXO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ALZN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMAL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMAM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMAO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR AMAOU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMAOW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AMBI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMBO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMBP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMH^G: No timezone found, symbol may be delisted
ERROR AMH^H: No timezone found, symbol may be delisted
ERROR AMK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMLX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMPG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMPGW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMPL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMPS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMPX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMRX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMTB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMTD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMTI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AMWL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANAB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANEB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANGH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANGHW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ANNX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANVS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANZU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANZUU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ANZUW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AOGO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AOGOU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AOGOW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AOMR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AOUT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APACW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR APCA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APCXW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR APE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APGB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APGN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APGNW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR API: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APLD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APLM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APLMW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APLS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APLT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APMI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APMIU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APMIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR APP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APPH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APPHW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR APPN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APRE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APRN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APTM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APTMU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APTMW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR APTV^A: No timezone found, symbol may be delisted
ERROR APXI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR APXIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR APYX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQNA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQNB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQNU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AQUNR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AQUNU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARBB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARBE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARBEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARBG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARBGW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARBK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARBKL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARCE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARDS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AREB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AREBW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AREC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARGO^A: No timezone found, symbol may be delisted
ERROR ARGX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARHS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARIS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARIZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARIZW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARKO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARKOW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARLO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARNC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARQQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARQQW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARQT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARR^C: No timezone found, symbol may be delisted
ERROR ARRW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARRWU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARRWW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARRY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARTE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR ARTEU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARTEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARTL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARTLW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ARVL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARVN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARYD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ARYE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASAI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASB^E: No timezone found, symbol may be delisted
ERROR ASB^F: No timezone found, symbol may be delisted
ERROR ASBA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASCAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ASCB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASCBR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ASCBW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ASGI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASLE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASLN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASNS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASPAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ASPI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASTI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASTL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASTLW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ASTR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASTS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ASTSW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ATAI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATAKR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ATAT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATCO^D: No timezone found, symbol may be delisted
ERROR ATCO^H: No timezone found, symbol may be delisted
ERROR ATCO^I: No timezone found, symbol may be delisted
ERROR ATCOL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATEK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATER: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATH^A: No timezone found, symbol may be delisted
ERROR ATH^B: No timezone found, symbol may be delisted
ERROR ATH^C: No timezone found, symbol may be delisted
ERROR ATH^D: No timezone found, symbol may be delisted
ERROR ATH^E: No timezone found, symbol may be delisted
ERROR ATHA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATIF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATIP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATLCL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATLCP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATLX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATMC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATMCR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ATMCU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATMU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATMV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATMVU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATNF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATNFW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ATUS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATXG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ATXI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AUB^A: No timezone found, symbol may be delisted
ERROR AUGX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AUID: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AULT^D: No timezone found, symbol may be delisted
ERROR AUR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AURA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AURC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AURCU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AURCW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AUROW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AUST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AUTL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AUUD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AUUDW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AUVI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AUVIP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVAH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVDX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVHI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVHIU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVHIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AVIR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVPT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVPTW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AVRO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVTE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AVTR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AWIN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AWINW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR AXLA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AXNX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AXS^E: No timezone found, symbol may be delisted
ERROR AYX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AZEK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AZUL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR AZYO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BAC^B: No timezone found, symbol may be delisted
ERROR BAC^E: No timezone found, symbol may be delisted
ERROR BAC^K: No timezone found, symbol may be delisted
ERROR BAC^L: No timezone found, symbol may be delisted
ERROR BAC^M: No timezone found, symbol may be delisted
ERROR BAC^N: No timezone found, symbol may be delisted
ERROR BAC^O: No timezone found, symbol may be delisted
ERROR BAC^P: No timezone found, symbol may be delisted
ERROR BAC^Q: No timezone found, symbol may be delisted
ERROR BAC^S: No timezone found, symbol may be delisted
ERROR BACA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BACK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BAER: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR BAERW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BAFN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BALY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BAM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BAND: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BANL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BAOS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BARK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BASE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BATL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBAI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBCP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBIG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBIO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBLG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBLGW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBLN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BBUC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BC^A: No timezone found, symbol may be delisted
ERROR BC^B: No timezone found, symbol may be delisted
ERROR BC^C: No timezone found, symbol may be delisted
ERROR BCAB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCAT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCDAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BCEL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCOW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCSA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCSAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCSAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BCSF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BCTXW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BCV^A: No timezone found, symbol may be delisted
ERROR BCYC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BDSX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BDTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEAM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEAT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEATW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BEDU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEEMW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BEKE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BENF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BENFW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BEP^A: No timezone found, symbol may be delisted
ERROR BEPC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEPH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEPI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BEST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR Failed to get ticker 'BF/A' reason: Expecting value: line 1 column 1 (char 0)
ERROR BF/A: No timezone found, symbol may be delisted
ERROR Failed to get ticker 'BF/B' reason: Expecting value: line 1 column 1 (char 0)
ERROR BF/B: No timezone found, symbol may be delisted
ERROR BFAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BFI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BFIIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BFLY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BFRG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BFRGW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BFRI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BFRIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BFS^D: No timezone found, symbol may be delisted
ERROR BFS^E: No timezone found, symbol may be delisted
ERROR BFST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BGRY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BGRYW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BGXX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHACW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BHAT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHFAL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHFAM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHFAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHFAO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHFAP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHIL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BHR^B: No timezone found, symbol may be delisted
ERROR BHR^D: No timezone found, symbol may be delisted
ERROR BHVN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIAF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIAFW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BIGC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIGZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BILI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BILL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR Failed to get ticker 'BIO/B' reason: Expecting value: line 1 column 1 (char 0)
ERROR BIO/B: No timezone found, symbol may be delisted
ERROR BIOR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIOS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIOSW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR BIOX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIP^A: No timezone found, symbol may be delisted
ERROR BIP^B: No timezone found, symbol may be delisted
ERROR BIPC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIPH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIPI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIRD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BITE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BITF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BIVI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BJ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BJDX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

In [51]:
#MYTE - "'float' object has no attribute 'upper'" 
unique_count1 = df['Symbol'].nunique()
print(unique_count1)

457

In [66]:
stock2 = stock[1001:2000]
stock_symbol2 = stock2["Symbol"]
symbol2 = stock_symbol2.tolist()
symbol2
symbol_test='BOOT'

In [67]:
df_test=pd.DataFrame()

ticker=yf.Ticker(symbol_test)
start_date = datetime(2012, 1, 1)
end_date = datetime(2016, 12, 31)
historical_data = ticker.history(start=start_date, end=end_date, interval='1d')
historical_data['Symbol']=symbol_test
historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Symbol
Date,,,,,,,,
2014-10-30 00:00:00-04:00,19.000000,19.500000,16.879999,17.450001,6884200,0.0,0.0,BOOT
2014-10-31 00:00:00-04:00,17.790001,18.139999,17.660000,17.750000,429100,0.0,0.0,BOOT
2014-11-03 00:00:00-05:00,17.559999,17.700001,17.500000,17.559999,112000,0.0,0.0,BOOT
2014-11-04 00:00:00-05:00,17.750000,17.750000,17.090000,17.379999,187700,0.0,0.0,BOOT
2014-11-05 00:00:00-05:00,17.139999,17.570000,16.910000,17.040001,361400,0.0,0.0,BOOT
...,...,...,...,...,...,...,...,...
2016-12-23 00:00:00-05:00,12.200000,12.810000,12.200000,12.650000,350100,0.0,0.0,BOOT
2016-12-27 00:00:00-05:00,12.630000,13.030000,12.630000,12.830000,130800,0.0,0.0,BOOT
2016-12-28 00:00:00-05:00,12.910000,13.440000,12.420000,12.570000,273100,0.0,0.0,BOOT
2016-12-29 00:00:00-05:00,12.640000,12.870000,12.480000,12.690000,287400,0.0,0.0,BOOT
2016-12-30 00:00:00-05:00,12.740000,12.760000,12.410000,12.520000,154200,0.0,0.0,BOOT

In [65]:
df2 = pd.DataFrame()

for i in symbol2:
    ticker = yf.Ticker(i)

    # Set the start and end dates for data retrieval
    start_date = datetime(2012, 1, 1)
    end_date = datetime(2016, 12, 31)

    historical_data = ticker.history(start=start_date, end=end_date, interval='1d')

    if historical_data.empty:
        continue

    historical_data['Symbol']=i
    df2 = df.append(historical_data)
    
df2

ERROR BKDT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR BKKT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Symbol
0,2012-01-03 00:00:00-05:00,23.208217,23.952900,23.143461,23.622650,4156394,0.0,0.0,A
1,2012-01-04 00:00:00-05:00,23.408962,23.544946,23.046332,23.434862,4651845,0.0,0.0,A
2,2012-01-05 00:00:00-05:00,23.234120,24.166592,23.130512,23.959377,6842651,0.0,0.0,A
3,2012-01-06 00:00:00-05:00,24.017661,24.322010,23.836348,24.218403,4711400,0.0,0.0,A
4,2012-01-09 00:00:00-05:00,24.360863,24.878904,24.263731,24.853003,4429563,0.0,0.0,A
...,...,...,...,...,...,...,...,...,...
2016-12-23 00:00:00-05:00,NaT,37.843437,37.976833,37.541851,37.657845,1176600,0.0,0.0,BKR
2016-12-27 00:00:00-05:00,NaT,37.785442,38.098629,37.657846,38.017433,2224500,0.0,0.0,BKR
2016-12-28 00:00:00-05:00,NaT,38.005827,38.116024,37.327256,37.530247,2255500,0.0,0.0,BKR
2016-12-29 00:00:00-05:00,NaT,37.454864,37.640456,37.124278,37.536060,1461300,0.0,0.0,BKR
2016-12-30 00:00:00-05:00,NaT,37.489660,37.907244,37.460659,37.681053,1872700,0.0,0.0,BKR

In [61]:
df2.to_csv('/Users/hp/SAD_Finance/stock_2.csv',index=False)
unique_count2 = df2['Symbol'].nunique()
print(unique_count2)
df2.head()

458

,index,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Symbol
0,0,2012-01-03 00:00:00-05:00,23.208217,23.952900,23.143461,23.622650,4156394,0.0,0.0,A
1,1,2012-01-04 00:00:00-05:00,23.408962,23.544946,23.046332,23.434862,4651845,0.0,0.0,A
2,2,2012-01-05 00:00:00-05:00,23.234120,24.166592,23.130512,23.959377,6842651,0.0,0.0,A
3,3,2012-01-06 00:00:00-05:00,24.017661,24.322010,23.836348,24.218403,4711400,0.0,0.0,A
4,4,2012-01-09 00:00:00-05:00,24.360863,24.878904,24.263731,24.853003,4429563,0.0,0.0,A

In [50]:
stock3 = stock[2001:3000]
stock_symbol3 = stock3["Symbol"]
symbol3 = stock_symbol3.tolist()

df3 = pd.DataFrame()

for i in symbol3:
    ticker = yf.Ticker(i)

    # Set the start and end dates for data retrieval
    start_date = datetime(2012, 1, 1)
    end_date = datetime(2016, 12, 31)

    historical_data = ticker.history(start=start_date, end=end_date, interval='1d')

    if historical_data.empty:
        continue

    historical_data['Symbol']=i
    df3 = df.append(historical_data)
    
df3 = df3.reset_index()
df3
df3.to_csv('/Users/hp/SAD_Finance/stock_3.csv',index=False)

ERROR DECA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DECAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DEN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DERM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DESP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DFH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DFLI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DFLIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DGHI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DHCA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DHCAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DHCNL: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DIBS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DICE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DISA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DISAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DISAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DIST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DISTR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DKDCA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DKDCW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DKNG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DLNG^A: No timezone found, symbol may be delisted
ERROR DLNG^B: No timezone found, symbol may be delisted
ERROR DLO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DLR^J: No timezone found, symbol may be delisted
ERROR DLR^K: No timezone found, symbol may be delisted
ERROR DLR^L: No timezone found, symbol may be delisted
ERROR DLY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DMA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DMAQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DMAQR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DMS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DMTK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DMYY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNAB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNAD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNLI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNMR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DNUT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOCN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOCS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOCU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOGZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOLE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOMA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOMO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOUG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DOYU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DPCSW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DPRO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DPSI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DRCT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DRCTW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DRH^A: No timezone found, symbol may be delisted
ERROR DRMA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DRMAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DRTS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DRTSW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DRUG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DRVN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DSAQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DSEY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DSGN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DSP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DSX^B: No timezone found, symbol may be delisted
ERROR DT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTIL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTOC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTOCU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTOCW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DTSS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DTW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DUETW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DUK^A: No timezone found, symbol may be delisted
ERROR DUKB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DUNE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DUNEU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DUNEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DUO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DUOL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DUOT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DWAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DWACU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR DWACW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR DX^C: No timezone found, symbol may be delisted
ERROR DYN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EACPW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EAF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EAR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EAST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EBC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EBET: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EBON: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECAT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECBK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR ECC           : No timezone found, symbol may be delisted
ERROR ECC^D: No timezone found, symbol may be delisted
ERROR ECCC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECCV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECCW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECCX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECF^A: No timezone found, symbol may be delisted
ERROR ECOR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECVT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ECXWW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EDBL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EDBLW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EDR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EDRY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EDTK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EDTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EEIQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EEX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EFC^A: No timezone found, symbol may be delisted
ERROR EFC^B: No timezone found, symbol may be delisted
ERROR EFC^C: No timezone found, symbol may be delisted
ERROR EFHT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EFHTR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EFHTW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EFSCP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EFSH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EFTR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EFTRW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EGGF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EGLX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EHAB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EIC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EICA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EJH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELBM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELEV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELVN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELYM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ELYS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMBC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMBK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMBKW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EMCG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMCGR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EMCGU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMCGW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EMLD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMLDU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EMLDW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ENCPW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ENER: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENERR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ENERW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ENFN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENLT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENOB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENSC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENTF: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENTFW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ENTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ENTXW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ENVX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EOCW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EOLS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EOSE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EOSEW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EP^C: No timezone found, symbol may be delisted
ERROR EPOW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EPR^C: No timezone found, symbol may be delisted
ERROR EPR^E: No timezone found, symbol may be delisted
ERROR EPR^G: No timezone found, symbol may be delisted
ERROR EPRT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EQC^D: No timezone found, symbol may be delisted
ERROR EQH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EQH^A: No timezone found, symbol may be delisted
ERROR EQH^C: No timezone found, symbol may be delisted
ERROR EQRX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EQRXW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EQX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ERAS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ERES: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ERESW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ERO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ERYP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESAB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESACU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESACW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR ESGRO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESGRP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESMT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESTA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ESTC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ET^C: No timezone found, symbol may be delisted
ERROR ET^D: No timezone found, symbol may be delisted
ERROR ET^E: No timezone found, symbol may be delisted
ERROR ETAO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ETI^: No timezone found, symbol may be delisted
ERROR ETNB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ETON: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ETRN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ETWO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR ETX           : No timezone found, symbol may be delisted

ERROR EUDA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EUDAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EVAX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVCM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVER: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVEX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVGO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVGOW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVGR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVGRU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVGRW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EVLO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVLV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVLVW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR EVTL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EVTV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EWCZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EWTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EXAI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EXFY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EXPI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EYE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EYEN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EZFL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR EZGO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR F^B: No timezone found, symbol may be delisted
ERROR F^C: No timezone found, symbol may be delisted
ERROR F^D: No timezone found, symbol may be delisted
ERROR FA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FACT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FAMI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FAT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FATBB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FATBP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FATBW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FATH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FATP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FATPU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FATPW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FAZE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FAZEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FBIOP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FBRT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FBRT^E: No timezone found, symbol may be delisted
ERROR FBRX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FCNCO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FCNCP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FCRX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FDMT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FEAM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FEDU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FEI           : No timezone found, symbol may be delisted
ERROR FEMY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FENC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FEXD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FEXDR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FEXDU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FEXDW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FFIE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FFIEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FGBIP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FGFPP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FGI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FGIWW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FGMC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FGMCW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FHLT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FHLTU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FHLTW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FHN^B: No timezone found, symbol may be delisted
ERROR FHN^C: No timezone found, symbol may be delisted
ERROR FHN^D: No timezone found, symbol may be delisted
ERROR FHN^E: No timezone found, symbol may be delisted
ERROR FHN^F: No timezone found, symbol may be delisted
ERROR FHTX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FIAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FICV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FICVU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FICVW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FIGS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FINS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FINV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FINW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FIP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FITBO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FITBP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FIXX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLAG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLFV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLFVR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FLGC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLJ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLME: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLNC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLNG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLUX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FLYW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FMIV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FMIVW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FNA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FNB^E: No timezone found, symbol may be delisted
ERROR FNCH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FND: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FNGR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FNKO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FNVT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FNVTU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR FNVTW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FOA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FOCS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FORA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FORG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FORL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FORLU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FORLW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FOSLL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FOUR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FOX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FOXA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FOXO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FPH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRBN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRBNW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FREE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FREEW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FREQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRES: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FREY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRGAP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRGE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRGT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRHC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRLA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRLAU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRLAW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRLN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRMEP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FROG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRSH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRSX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRT^C: No timezone found, symbol may be delisted
ERROR FRXB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FRZA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSBC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSCO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSEA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSLY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSNB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSRX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSRXU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FSRXW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FTAIM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTAIN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTAIO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTAIP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTCH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTCI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTDR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTHM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTHY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTII: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTIIU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FTIIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FUBO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FULC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FULTP: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FUSN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FUTU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FUV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FVRR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FWAC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FWRG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FXCO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FXCOW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR FXLV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FYBR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR FZT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAB^G: No timezone found, symbol may be delisted
ERROR GAB^H: No timezone found, symbol may be delisted
ERROR GAB^K: No timezone found, symbol may be delisted
ERROR GAINL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAINN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAINZ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAM^B: No timezone found, symbol may be delisted
ERROR GAMB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAMC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAMCU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAMCW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GAME: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GANX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GAQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GATE: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GATEU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GATEW: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GATO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GB: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GBBK: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GBBKR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GBBKW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GBIO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GBNH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GBNY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GBTG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GCMG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GCMGW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GCT: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GDEV: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GDEVW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GDHG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GDL^C: No timezone found, symbol may be delisted
ERROR GDNR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

ERROR GDNRW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GDRX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GDST: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GDSTR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GDSTW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GDTC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GDV^H: No timezone found, symbol may be delisted
ERROR GDV^K: No timezone found, symbol may be delisted
ERROR GDYN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GECCM: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GECCN: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GECCO: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GEGGL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GEHC: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GEHI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GENI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GENQ: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GETR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GETY: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFAI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFAIW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GFGD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFGDR: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GFGDU: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFGDW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GFL: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFOR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GFX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GGAA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GGAAW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GGN^B: No timezone found, symbol may be delisted
ERROR GGR: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GGROW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GGT^E: No timezone found, symbol may be delisted
ERROR GGT^G: No timezone found, symbol may be delisted
ERROR GH: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GHG: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GHIX: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GHIXW: Period '1mo' is invalid, must be one of ['1d', '5d']
ERROR GHLD: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GHRS: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GHSI: Data doesn't exist for startDate = 1325394000, endDate = 1483160400
ERROR GIA: Data doesn't exist for startDate = 1325394000, endDate = 1483160400

In [57]:
unique_count3 = df3['Symbol'].nunique()
print(unique_count3)
df3

458

,index,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Symbol
0,0,2012-01-03 00:00:00-05:00,23.208217,23.952900,23.143461,23.622650,4156394,0.0,0.0,A
1,1,2012-01-04 00:00:00-05:00,23.408962,23.544946,23.046332,23.434862,4651845,0.0,0.0,A
2,2,2012-01-05 00:00:00-05:00,23.234120,24.166592,23.130512,23.959377,6842651,0.0,0.0,A
3,3,2012-01-06 00:00:00-05:00,24.017661,24.322010,23.836348,24.218403,4711400,0.0,0.0,A
4,4,2012-01-09 00:00:00-05:00,24.360863,24.878904,24.263731,24.853003,4429563,0.0,0.0,A
...,...,...,...,...,...,...,...,...,...,...
512949,2016-12-23 00:00:00-05:00,NaT,8.416378,8.433484,8.404973,8.422080,109400,0.0,0.0,GHY
512950,2016-12-27 00:00:00-05:00,NaT,8.467695,8.467695,8.399268,8.416375,146500,0.0,0.0,GHY
512951,2016-12-28 00:00:00-05:00,NaT,8.445080,8.496750,8.445080,8.496750,197000,0.1,0.0,GHY
512952,2016-12-29 00:00:00-05:00,NaT,8.508232,8.531196,8.473786,8.508232,366800,0.0,0.0,GHY
512953,2016-12-30 00:00:00-05:00,NaT,8.536940,8.577128,8.513976,8.548423,275200,0.0,0.0,GHY

In [ ]:
stock4 = stock[3001:4000]
stock_symbol4 = stock4["Symbol"]
symbol4 = stock_symbol4.tolist()

df4 = pd.DataFrame()

for i in symbol4:
    ticker = yf.Ticker(i)

    # Set the start and end dates for data retrieval
    start_date = datetime(2012, 1, 1)
    end_date = datetime(2016, 12, 31)

    historical_data = ticker.history(start=start_date, end=end_date, interval='1d')

    if historical_data.empty:
        continue

    historical_data['Symbol']=i
    df4 = df.append(historical_data)
    
df4 = df4.reset_index()
df4.to_csv('/Users/hp/SAD_Finance/stock_4.csv',index=False)
df4

In [ ]:
unique_count4 = df4['Symbol'].nunique()
print(unique_count4)